"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](surface0)\
$directory\
[î‚°](bg:rosewater fg:surface0)\
$username\
$hostname\
$time\
[î‚°](bg:pink fg:rosewater)\
$git_branch\
$git_status\
$git_metrics\
[î‚°](bg:red fg:pink)\
$ruby\
[î‚°](bg:sky fg:red)\
$nodejs\
[î‚°](bg:blue fg:sky)\
$kubernetes\
[î‚°](bg:yellow fg:blue)\
$jobs\
$cmd_duration\
[î‚´](fg:yellow)
$character\
"""

palette = 'catppuccin_mocha'

[directory]
style = 'bg:surface0'
format = '[$path ]($style)[$read_only]($style)'
read_only = 'ðŸ”’ '

[username]
show_always = true
format = '[ $user]($style)'
style_user = 'bg:rosewater fg:surface0'

[hostname]
ssh_only=false
format = '[@$ssh_symbol$hostname ]($style)'
style = 'bg:rosewater fg:surface0'

[time]
disabled = false
style = 'bg:rosewater fg:surface0'
format = '[ðŸ•™$time ]($style)'

[git_branch]
format = '[ $symbol$branch]($style)'
style = 'bg:pink fg:surface0'

[git_status]
format = '[ \[$all_status$ahead_behind\] ]($style)'
style = 'bg:pink fg:surface0'

[git_metrics]
disabled = false
added_style = 'bg:pink fg:added_color'
deleted_style = 'bg:pink fg:deleted_color'
format = '[+$added]($added_style)[/](bg:pink fg:surface0)[-$deleted]($deleted_style)[ ](bg:pink fg:surface0)'

[ruby]
format = '[ $symbol ($version )]($style)'
style = 'bg:red fg:surface0'
symbol = 'îž‘'

[nodejs]
disabled = false
format = '[ $symbol$version ](bg:sky fg:surface0)'
detect_files = ['package.json']

[jobs]
style = 'bg:yellow fg:surface0'
format = '[ $symbol$number]($style)'
number_threshold = 1

[cmd_duration]
format = '[ took $duration ]($style)'
style = 'bg:yellow fg:surface0'

[kubernetes]
disabled = false
format = '[ $symbol$context ]($style)'
style = 'bg:blue fg:surface0'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
added_color = "#009000"
deleted_color = "#c00000"
